### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by whistle003** [blog-misaka/naiveproxy-script#2]
flag provided but not defined: -w
usage: env [-json] [var ...]
Run 'go help env' for details.
can't load package: package github.com/caddyserver/xcaddy/cmd/xcaddy@latest: cannot find package "github.com/caddyserver/xcaddy/cmd/xcaddy@latest" in any of:
        /usr/lib/go-1.10/src/github.com/caddyserver/xcaddy/cmd/xcaddy@latest (from $GOROOT)
        /root/go/src/github.com/caddyserver/xcaddy/cmd/xcaddy@latest (from $GOPATH)
naiveproxy.sh: line 62: /root/go/bin/xcaddy: No such file or directory

**Comment by blog-misaka** [comment]
您好！方便提供下你的VPS所安装的系统吗？

**Comment by blog-misaka** [comment]
更新了脚本，你可以重新试试看

**Comment by whistle003** [comment]
> 更新了脚本，你可以重新试试看

感谢大佬关注我的问题，现在已经安装上了，我的是racknerd的vps，系统是ubuntu20.4,现在部署成功以后，小火箭连接可以ping通，但是没有网络。还有就是希望可以内置一下自定义端口功能，谢谢！

**Comment by hiandy22** [comment]
试试shadowrocket 打开padding（也叫填充）

**Comment by whistle003** [comment]
> 试试shadowrocket 打开padding（也叫填充）

打开以后好了！感谢！是否可以内置一下自定义端口？

**Comment by blog-misaka** [comment]
@whistle003 到时候考虑一下

**Comment by whistle003** [comment]
> @whistle003 到时候考虑一下

多谢！
