### ISSUE TITLE
脚本下载caddy失败

### ISSUE THREAD

**Issue by hanyugang** [blog-misaka/naiveproxy-script#4]
--2022-10-30 14:55:51--  https://gitlab.com/misakablog/naiveproxy-script/-/raw/main/files/caddy-linux-amd64
Resolving gitlab.com (gitlab.com)... 2606:4700:90:0:f22e:fbec:5bed:a9b9, 172.65.251.78
Connecting to gitlab.com (gitlab.com)|2606:4700:90:0:f22e:fbec:5bed:a9b9|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://gitlab.com/users/sign_in [following]
--2022-10-30 14:55:52--  https://gitlab.com/users/sign_in
Reusing existing connection to [gitlab.com]:443.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2022-10-30 14:55:52 ERROR 503: Service Temporarily Unavailable.

脚本从gitlab下载caddy，被重定向到登录页面，无法完成下载

**Comment by halton** [comment]
same error, https://gitlab.com/misakablog/naiveproxy-script/-/raw/main/files/caddy-linux-amd64 is not available.
